frases = [
    "Acredite em si mesmo e tudo será possível.",
    "Não espere por oportunidades, crie-as.",
    "Cada dia é uma nova chance para mudar sua vida.",
    "O sucesso é a soma de pequenos esforços repetidos todos os dias.",
    "Você é mais forte do que imagina.",
    "Persista. Se fosse fácil, qualquer um faria.",
    "A jornada de mil milhas começa com um único passo.",
    "Não tenha medo de recomeçar. É uma chance de fazer melhor.",
    "A única limitação é aquela que você acredita ter.",
    "Sonhe grande, comece pequeno, aja agora.",
    "A vida recompensa a coragem.",
    "A disciplina é a ponte entre metas e conquistas.",
    "A melhor maneira de prever o futuro é criá-lo.",
    "Transforme obstáculos em degraus para o sucesso.",
    "Você não precisa ser perfeito para começar, mas precisa começar para ser perfeito.",
    "Não desista, os grandes sonhos levam tempo.",
    "Não compare seu capítulo 1 com o capítulo 20 de alguém.",
    "Acredite: o melhor ainda está por vir.",
    "A ação é a chave fundamental para todo sucesso.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "Nunca é tarde para ser quem você poderia ter sido.",
    "Seja mais forte do que a sua melhor desculpa.",
    "A coragem não é ausência de medo, é a decisão de que algo é mais importante que o medo.",
    "Você nunca saberá até tentar.",
    "Tenha fé no processo.",
    "Levante com determinação. Durma com satisfação.",
    "A vitória pertence ao mais perseverante.",
    "Acredite no seu potencial infinito.",
    "Você é capaz de coisas incríveis.",
    "Não importa a velocidade. Vá no seu ritmo, mas não pare.",
    "Todo esforço tem sua recompensa.",
    "Você é a única pessoa que pode limitar o seu crescimento.",
    "Fracasso não é o fim, é uma lição disfarçada.",
    "Construa o hábito, e o hábito constrói você.",
    "Pequenas vitórias diárias levam ao sucesso duradouro.",
    "Seja constante, não perfeito.",
    "Não espere motivação, construa disciplina.",
    "Comece onde está. Use o que tem. Faça o que puder.",
    "Você já venceu só por não ter desistido.",
    "Sonhos não funcionam a menos que você trabalhe por eles.",
    "Acredite mais em você e menos nos seus medos.",
    "Nada muda se você não mudar.",
    "O impossível é apenas uma opinião.",
    "Toda grande conquista começa com a decisão de tentar.",
    "Foco, força e fé.",
    "Seja o motivo do seu próprio orgulho.",
    "Hoje é o melhor dia para começar.",
    "Viva com propósito.",
    "Você não está sozinho. Continue.",
    "Sua persistência será sua maior aliada."
]